export type Campings = 
    {id: number,
    nombre_camping: string,
    descripcion_camping: string,
    direccion: string,
    telefono: string,
    longitud: string,
    latitud: string,
    prop_camping_Id: number,
    cerrado_fecha_desde: string, 
    cerrado_fecha_hasta: string, 
    localidad: string,
    id_localidad:number,
    provincia: string,
    id_provincia:number,
    categoria: string,
    id_categoria:number,
    cantidad_estrellas: number,
    duchas: number,
    baños: number,
    mascotas: number,
    rodantes: number,
    proveduria: number,
    salon_sum: number,
    restaurant: number,
    vigilancia: number,
    pileta: number,
    estacionamiento: 1,
    juegos_infantiles: number,
    maquinas_gimnasia: number,
    wifi: number,
    parcela_techada: number,
    parcela_agua_en_parcela: number,
    parcela_iluminacion_toma_corriente: number,
    parcela_superficie: number,
    descripcion_periodo: string,
    descripcion_periodo_agua: string,
    precio: number,
    imagenes: Array<string>
}

export type User = {
    id: number,
    nombre_completo: string, 
    email: string,
    numero_celular: string,
    dni: string,
    direccion: string,
    tipo: number,
    token: string
}